apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fmzm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-fmzm@sha256:0d295f0488b7d23688a900795ae1bf1a652b92ab3bc27b76a2a94a9e4022156b
        name: my-nodejs
        resources: {}
status: {}
